package net.projecteuler.challenge;

import net.projecteuler.challenge.util.EulerUtil;

/**
 * Created by steve on 8/6/15.
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Verified Correct
 */
public class Problem2 {

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        int result = 0, fibonacciValue = 0;
        for(int i = 0; fibonacciValue < 4000000; i++){
            fibonacciValue = EulerUtil.fibonacci(i);
            if(EulerUtil.isEven(fibonacciValue)){
                result += fibonacciValue;
            }
        }
        System.out.println(result);
        System.out.println(EulerUtil.getExecutionTime(start, System.currentTimeMillis()));
    }
}
